[build]
  base = "cloudflare-pages"
  publish = "public"

[functions]
  directory = "netlify/functions"

[images]
  remote_images = [
    "https:\\/\\/(?:[^\\/]+\\.)?kinopoiskapiunofficial\\.tech\\/.*",
    "https:\\/\\/(?:[^\\/]+\\.)?kinopoisk\\.ru\\/.*",
    "https:\\/\\/(?:[^\\/]+\\.)?yandex\\.net\\/.*",
    "https:\\/\\/(?:[^\\/]+\\.)?yandex\\.ru\\/.*",
    "https:\\/\\/(?:[^\\/]+\\.)?kinopoisk\\.cloud\\/.*"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
